//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncyclopediaSecond
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorylink
    {
        public int cl_from { get; set; }
        public string cl_to { get; set; }
        public string cl_sortkey { get; set; }
        public string cl_timestamp { get; set; }
        public string cl_sortkey_perfix { get; set; }
        public string cl_collation { get; set; }
        public string cl_type { get; set; }
    }
}
