//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncyclopediaSecond
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int cat_id { get; set; }
        public string cat_title { get; set; }
        public int cat_pages { get; set; }
        public int cat_subcats { get; set; }
        public int cat_files { get; set; }
    }
}
