//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncyclopediaSecond
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public string img_name { get; set; }
        public int img_size { get; set; }
        public int img_width { get; set; }
        public int img_height { get; set; }
        public string img_metadata { get; set; }
        public int img_bits { get; set; }
        public string img_media_type { get; set; }
        public string img_major_mime { get; set; }
        public string img_minor_mime { get; set; }
        public string img_description { get; set; }
        public long img_description_id { get; set; }
        public int img_user { get; set; }
        public string img_user_text { get; set; }
        public long img_actor { get; set; }
        public string img_timestamp { get; set; }
        public string img_sha1 { get; set; }
        public byte img_deleted { get; set; }
    }
}
