//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncyclopediaSecond
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagelink
    {
        public int il_from { get; set; }
        public string il_to { get; set; }
        public int il_from_namespace { get; set; }
    }
}
