//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncyclopediaSecond
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPENXMLTestingEntities1 : DbContext
    {
        public OPENXMLTestingEntities1()
            : base("name=OPENXMLTestingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<XMLwithOpenXML> XMLwithOpenXMLs { get; set; }
        public virtual DbSet<categorylink> categorylinks { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<imagelink> imagelinks { get; set; }
    }
}
